name: "Plan2"
Plan:
  - resource: "Interface"
    operation: "C"
    instanceName: "I1"

  - resource: "Interface"
    operation: "C"
    instanceName: "I2"

  - resource: "Auth"
    operation: "C"
    instanceName: "Auth1"

  - resource: "Availability"
    operation: "C"
    instanceName: "Availability1"
    dependentOn: ["I1"]

  - resource: "Availability"
    operation: "C"
    instanceName: "Availability2"
    dependentOn: [ "I2" ]
    verify:
      name: "Availability2"

  - resource: "Notification"
    operation: "C"
    instanceName: "Notification7"
    dependentOn: ["Availability1"]

  - resource: "Interface"
    operation: "R"
    name: "Interface1"
    filters:
      - name: "DummyValue"
    verify:
        name: "DummyValue"

  - resource: "Interface"
    operation: "U"
    instanceName: "I1"
    fields:
      name: "I3"
    dependentOn: []

  - resource: "Availability"
    operation: "U"
    instanceName: "Availability1"
    fields:
      name: "Availability3"
    dependentOn: ["I3"]


